# Generated by Django 4.2.5 on 2024-01-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codegiggles_app', '0003_snippet_dislikes_snippet_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
